### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI_532_Cancer-Incidence#10]
* Your dataset selection is very interesting and the justification is clear.
* The decision of keeping the 10 most and least incident types of cancer is not obvious. Further detail should be provided, for example, I wonder why not the top 20?
* Maps are good visuals in shiny to show some information about the dataset. But in your case, I understand it is only for selecting a province (user input). This may not be as attractive to the user as if you were to also display some information about cancer incidence in the province within the map.
* Overall your sketch is well done. I’m just confused about the variables plotted, would only cancer types incidences be there or are the other variables you are using visible in the plot as well?

**Comment by rachelkriggs** [comment]
We decided not to subset to just 10 most and least incident types. We have kept all of the cancer types in the dataset.
