### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bettybhzhou** [UBC-MDS/DSCI_532_Cancer-Incidence#17]
Pros:
- I really like the trend tab, which provided a very good overview of the trend.
- I liked how you only showed the relevant widgets that corresponded to each tab.
- The time series plot is informative and easy to understand.

Improvements:
- Map is unresponsive to changes to the widgets. I could not figure out why the map was present. 
- Separate the map and time series visualization into different tabs.
- Trend tab  'variable' drop down menu does not change the axis of the visualization, therefore, try to hook-up the variable drop down menu to visualization.

**Comment by rachelkriggs** [comment]
Thank you for the feedback! We are implementing what we can.
