### ISSUE TITLE
Feedback from Richie

### ISSUE THREAD

**Issue by rzitomer** [UBC-MDS/DSCI_532_Cancer-Incidence#18]
- App takes a while to load.
- Some small data cleaning needed - for example, I see values like 'All Cancer' and 'ALL' in the cancer filter.
- Would be nice to see a short written documentation of what information the app is giving to you and how to use it.
- Good title (short and specific)
- Might make sense to display how many total cases the time series graph is based on. Otherwise you could be basing the y-values on a low number of data points (e.g. a specific type of cancer for 0-14 yo females might rely on a very small number)
- Better tab names than "Time series" and "Trend"
- Need to fix "Trend" graph to be responsive to filter
- Make "Trend" graph a histogram as opposed to a scatterplot?
- Make clear what year "Trend" is showing data from (or have multiple graphs for multiple years)
- Allow user select multiple different line graphs in 'Time Series' (e.g. compare colon to breast cancer)

**Comment by rachelkriggs** [comment]
- smaller data should make app faster to load
- cleared up 'ALL' confusion
- added more descriptive tab names
- trend graph now responsive to filters
- multiple cancers can now be selected
