### ISSUE TITLE
Milestone 2 TA feedback

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI_532_Cancer-Incidence#21]
* Organized repo
* You are missing screenshots to document functionality
* Considering changing the style of the plot from the first tab, it’s hard to read. Also add more ticks to the axis.
* For the map, I suggest having a tab for it, presenting a heat map of the provinces and changing with inputs from the side bar you have in your initial tab (except for region). 
* In choose cancer type you have both `ALL` and `All cancers`. What is the difference? It’s confusing.
* You could add the year slider in the second tab as well. Or think about another functionality if you are not using the select variable anymore. 
* Code is readable and well commented :)

**Comment by rachelkriggs** [comment]
- map put in separate tab as a placeholder for next version (still not functional).
- year variable added to second tab.
